version: 2.1

# define the parameters from the setup config.
parameters:
  always-continue:
    type: boolean
    default: false
  pipeline-samplelib1:
    type: boolean
    default: false
  pipeline-service1:
    type: boolean
    default: false
  pipeline-service2:
    type: boolean
    default: false

jobs:
  no-updates:
    executor: bookworm
    steps:
      - run: echo "No updates have been made"

workflows:
  no-update-workflow:
    jobs:
      - no-updates